#ifndef SHAREDBASE_H_INCLUDED
#define SHAREDBASE_H_INCLUDED

#pragma warning( push )
#pragma warning( disable : 4514 )  // unreferenced inline function has been removed
#pragma warning( disable : 4711 )  // function selected for automatic inline expansion

#include "SharedBase/ge_def.h"
#include "SharedBase/ge_types.h"
#include "SharedBase/ge_system.h"
#include "SharedBase/ge_timer.h"
#include "SharedBase/ge_clock.h"
#include "SharedBase/ge_fpuadmin.h"
#include "SharedBase/ge_criticalsection.h"
#include "SharedBase/ge_locksystem.h"
#include "SharedBase/ge_mempool.h"
#include "SharedBase/ge_memorysubsystemstack.h"
#include "SharedBase/ge_memoryadmin.h"
#include "SharedBase/ge_memory.h"
#include "SharedBase/ge_memoryguard.h"
#include "SharedBase/ge_validatememory.h"
#include "SharedBase/ge_enginedialogs.h"
#include "SharedBase/ge_arraybase.h"
#include "SharedBase/ge_arraymap.h"
#include "SharedBase/ge_objarray.h"
#include "SharedBase/ge_valarray.h"
#include "SharedBase/ge_ptrarray.h"
#include "SharedBase/ge_autoptrarray.h"
#include "SharedBase/ge_arraysortbase.h"
#include "SharedBase/ge_mapbase.h"
#include "SharedBase/ge_valmap.h"
#include "SharedBase/ge_objmap.h"
#include "SharedBase/ge_objstack.h"
#include "SharedBase/ge_queuebase.h"
#include "SharedBase/ge_valqueue.h"
#include "SharedBase/ge_gcmemgeneration.h"
#include "SharedBase/ge_gcmem.h"
#include "SharedBase/ge_messageadmin.h"
#include "SharedBase/ge_message.h"
#include "SharedBase/ge_erroradmin.h"
#include "SharedBase/ge_error.h"
class bCUnicodeString;
#include "SharedBase/ge_string.h"
#include "SharedBase/ge_stringmap.h"
#include "SharedBase/ge_unicodestring.h"
#include "SharedBase/ge_guid.h"
#include "SharedBase/ge_datetime.h"
#include "SharedBase/ge_variant.h"
#include "SharedBase/ge_profilenode.h"
#include "SharedBase/ge_profilemanager.h"
#include "SharedBase/ge_istream.h"
#include "SharedBase/ge_ostream.h"
#include "SharedBase/ge_iostream.h"
#include "SharedBase/ge_commandline.h"
#include "SharedBase/ge_file.h"
#include "SharedBase/ge_filesystem.h"
#include "SharedBase/ge_memorystream.h"
#include "SharedBase/ge_nullstream.h"
#include "SharedBase/ge_postream.h"
class bCMd5;
#include "SharedBase/ge_propertyid.h"
#include "SharedBase/ge_md5.h"
#include "SharedBase/ge_bitfield.h"
#include "SharedBase/ge_trackbitfield.h"
#include "SharedBase/ge_point.h"
#include "SharedBase/ge_rect.h"
class bCMatrix2;
#include "SharedBase/ge_vector2.h"
#include "SharedBase/ge_matrix2.h"
#include "SharedBase/ge_sphericalrotation.h"
class bCMatrix;
class bCMatrix3;
#include "SharedBase/ge_vector.h"
#include "SharedBase/ge_vector4.h"
class bCEulerAngles;
class bCQuaternion;
#include "SharedBase/ge_axisangle.h"
#include "SharedBase/ge_eulerangles.h"
#include "SharedBase/ge_quaternion.h"
#include "SharedBase/ge_matrix3.h"
#include "SharedBase/ge_motion.h"
#include "SharedBase/ge_matrix.h"
#include "SharedBase/ge_eigenvector.h"
#include "SharedBase/ge_capsule.h"
class bCBox;
class bCRay;
#include "SharedBase/ge_plane.h"
class bCFrustum;
class bCLine;
class bCSphere;
class bCStretch;
class bCUnitedRay;
#include "SharedBase/ge_triangle.h"
#include "SharedBase/ge_ray.h"
#include "SharedBase/ge_line.h"
#include "SharedBase/ge_stretch.h"
#include "SharedBase/ge_unitedray.h"
#include "SharedBase/ge_volume.h"
#include "SharedBase/ge_box.h"
#include "SharedBase/ge_frustum.h"
#include "SharedBase/ge_sphere.h"
class bCInfDoubleCylinder;
#include "SharedBase/ge_infcylinder.h"
#include "SharedBase/ge_infdoublecylinder.h"
#include "SharedBase/ge_orientedbox.h"
#include "SharedBase/ge_octtree.h"
#include "SharedBase/ge_flexiblevertexformat.h"
#include "SharedBase/ge_flexiblevertexptr.h"
#include "SharedBase/ge_mersennetwister.h"
#include "SharedBase/ge_random.h"
#include "SharedBase/ge_range1.h"
#include "SharedBase/ge_range2.h"
#include "SharedBase/ge_range3.h"
#include "SharedBase/ge_range4.h"
#include "SharedBase/ge_noise.h"
#include "SharedBase/ge_ebertnoise.h"
#include "SharedBase/ge_peacheynoise.h"
#include "SharedBase/ge_perlinnoise.h"
class bCByteAlphaColor;
class bCByteColor;
class bCFloatAlphaColor;
class bCFloatColor;
class bCFloatColorHSV;
#include "SharedBase/ge_colorbase.h"
#include "SharedBase/ge_bytecolor.h"
#include "SharedBase/ge_bytealphacolor.h"
#include "SharedBase/ge_floatcolor.h"
#include "SharedBase/ge_floatalphacolor.h"
#include "SharedBase/ge_floatcolorhsv.h"
#include "SharedBase/ge_xmlparsernode.h"
#include "SharedBase/ge_xmlparser.h"
#include "SharedBase/ge_classnamebase.h"
#include "SharedBase/ge_classname.h"
class bCPropertyConverter;
#include "SharedBase/ge_propertyconverterptr.h"
class bCObjectBase;
#include "SharedBase/ge_propertyconverter.h"
class bCPropertyObjectTypeBase;
#include "SharedBase/ge_propertytypebase.h"
#include "SharedBase/ge_propertyobjecttypebase.h"
#include "SharedBase/ge_objectbase.h"
#include "SharedBase/ge_objectrefbase.h"
#include "SharedBase/ge_event.h"
#include "SharedBase/ge_thread.h"
#include "SharedBase/ge_threadex.h"
#include "SharedBase/ge_threadobjectrefbase.h"
#include "SharedBase/ge_accessorcreator.h"
#include "SharedBase/ge_accessorpropertyobject.h"
#include "SharedBase/ge_accessorproperty.h"
#include "SharedBase/ge_zoneraster.h"

#include "SharedBase/ge_obsoleteclass.h"
#include "SharedBase/ge_propertycontainer.h"

GE_C_LINKAGE GE_DLLIMPORT GEFloat g_fFOV;

#pragma warning( pop )

#endif
