#include "../Script.h"

GS_DEFINE_PROPERTYSET_ACCESSOR( PSRoutine )

GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, AIDelay )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, AIMode )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, ActionString )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, AmbientAction )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, CommandTime )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, EndAttackTimestamp )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, HitDirection )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, LastAIMode )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, LockAIInterrupt )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, LockAIResult )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, Routine )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, RoutineChanged )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, StatePosition )
GS_DEFINE_PROPERTY_ACCESSOR( PSRoutine, TaskPosition )
